### ISSUE TITLE
matching is always considered a use of the place, even with `_` patterns

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/project-rfc-2229#27]
In this example [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0b815bf698d04bb98f5673bb736f9179):

```rust
    let foo = [1, 2, 3];
    let c = || match foo { _ => () };
```

the `match foo` winds up registering a read of `foo` in the `ExprUseVisitor`. Note that the behavior here is different from `let _ = foo`. This is also somewhat inconsistent with the borrow checker, which considers `match foo { _ => () }` to not be a use (i.e., this code compiles, [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1b693afc074e1afc740b0ca8deef897b)):

```rust
let mut x = 1;
let y = &x;
match x { _ => () }
drop(y);
```

**Comment by arora-aman** [comment]
- From a back-compat perspective, inside closures do we want to stop capturing the place that is being matched on? 
- If yes, the fix is kind of _simple_ for capture analysis. Clippy uses ExprUseVisitor which makes this a little tricky.
- For capture analysis, we just remove [this line]
- The reason it works is:
  - When `capture_disjoint_fields` is enabled, the case described above falls under #24 
  - When it's not enabled, since we capture everything that is mentioned inside the closure, we will end up capturing
     the discriminant as well, similar to how we have been doing things so far.

What remains is to see if this breaks clippy. If it does, how they use it will define how we end up handling the problem.


[this line]: https://github.com/rust-lang/rust/blob/502c477b3417f18e4e45b4e6e37da9965a033051/compiler/rustc_typeck/src/expr_use_visitor.rs#L225
