### ISSUE TITLE
Handle `#[repr(packed)]` with feature gate

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/project-rfc-2229#33]
```
#[repr(packed)]
struct Foo { x: u8, y: u8 }

fn main(foo: Foo) {
    let c = || {
        let z: &u8 = unsafe { &foo.x };
    
    };
    // cannot capture `foo.x` at the point of closure *creation*, must just capture `foo`
    // In your code:
    // You'll see a place like `[foo, x]`
    // if you have a field projection where the field is defined in a `#[repr(packed)]` struct, you need to capture the struct itself
}
```

**Comment by arora-aman** [comment]
- If foo.x is being moved, that's safe to do
- If we do an Imm/Mut Borrow to the foo.x then it's going to be an unsafe operation and we stop at the struct and prevent capturing the field.

**Comment by arora-aman** [comment]
We only want to truncate if the alignment is not 1. eg: when using `u8`s

**Comment by nikomatsakis** [comment]
Note: There was an interesting case that we discussed on 2021-03-03. If you have a closure that accesses a packed field:

```rust
#[repr(packed)] struct Foo { x: String }

let f: Foo;
let c = || {
    let x = &f.x;
    drop(f.x);
}
```

This could conceivably be safe because the closure desugaring will move out of `f.x` and hence the packed field is never actually borrowed. However, we choose to still truncate (and hence make this unsafe) for consistency and lack of surprise. If the closure were inlined into its caller, for example, you would get errors because of the lack of an unsafe block.

The workaround for users is to add `let tmp = f.x` before the closure, just as you would in non-closure code.
