### ISSUE TITLE
`capture!` macro

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/project-rfc-2229#40]
We should create a `capture!(x)` macro that expands to `drop(&x)`. This will be used with the migrations.

**Comment by nikomatsakis** [comment]
Simplest possible macro is something like this, but which supports a trailing comma:

```rust
macro_rules! capture {
    ($($x:ident),*) => { // NB using ident
       drop(&($($x),*))
    }
}
```

`capture!(y)` but not `capture(y.0)`, though the latter would probably...just work?

Given this example, user could potentially "optimize" to some subfield:

```rust
|| {
    capture!(x.0);
    drop((&x.0.0, &x.0.1, &x.0.2));
}
```

**Comment by nikomatsakis** [comment]
Possible location might be `std::marker::capture!(...)`, should check with @rust-lang/libs to see what people think.

(Hi libs people! 👋 )

**Comment by luiswirth** [comment]
I'm lacking full context, but I feel like the `captures!(x)` macro should rather expand to `let _ = &x` than `drop(&x)`. This would drop the variable at the end of the scope/closure instead of immediately dropping.

Isn't this more suited for the purpose of this migration, since it has the same behaviour as capturing the variable pre-RFC2229 and having it drop at the end of the closure?

Again I'm just assuming that's the purpose of this macro because I don't have much context... Sorry if I'm wrong.
