### ISSUE TITLE
Tie use of feature to the current edition

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/project-rfc-2229#43]
Today we use the `#![feature]` to decide whether to use new-style capture, but we should also consider the 2021 edition.

**Comment by arora-aman** [comment]
- We'd probably want to look into tying the lint to edition as well

**Comment by m-ou-se** [comment]
Is there anything blocking this?

**Comment by nikomatsakis** [comment]
I'm going to assign this to @arora-aman -- feel free to reassign.

**Comment by arora-aman** [comment]
- Feature enabled by default on edition 2021
- Set future incompabile in lint metadata to edition 2021

**Comment by m-ou-se** [comment]
For the lint:

- [ ] Change the lint name to something that reads well in `allow()` and `deny()`. (What exactly does it allow or deny?)
  - Happening in https://github.com/rust-lang/rust/pull/86717
- [x] Mark it as `future_incompatible`: https://github.com/rust-lang/rust/pull/86673
- [x] Refer to `Rust 2021` instead of the unstable feature name: https://github.com/rust-lang/rust/pull/86673
  - [x] in the lint messages: https://github.com/rust-lang/rust/pull/86673
  - [x] in the lint documentation: https://github.com/rust-lang/rust/pull/86673
- [x] Add a link to the edition guide: https://github.com/rust-lang/rust/pull/86673

**Comment by nikomatsakis** [comment]
This is now done.
