### ISSUE TITLE
Use hir::Place in closure_captures

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/project-rfc-2229#7]
Ensure that field/member are marked borrowed/moved instead of variable hir_id.

This would look something like https://github.com/rust-lang/project-rfc-2229/blob/master/closure_captures.md

**Comment by arora-aman** [comment]
Depends on #12 and #2

**Comment by arora-aman** [comment]
`closure_captures` generated at: https://github.com/rust-lang/rust/blob/28946b3486d507418b8a4acb92d5e2baae193d65/src/librustc_typeck/check/upvar.rs#L115

Related to [InferBorrowKind](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/check/upvar/struct.InferBorrowKind.html) defined in `rustc_typeck/check/upvar.rs`

and might require [adjust_upvar_captures](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/check/upvar/struct.InferBorrowKind.html#structfield.adjust_upvar_captures) to use a Place similar to `closure_captures`

This is then called from expr_use_visitor: https://github.com/rust-lang/rust/blob/28946b3486d507418b8a4acb92d5e2baae193d65/src/librustc_typeck/expr_use_visitor.rs#L554

**Comment by arora-aman** [comment]
https://rustc-dev-guide.rust-lang.org/closure.html?highlight=InferBorrowKind#inferences-in-the-compiler

**Comment by nikomatsakis** [comment]
Current status:

* Outlined the data structures to store minimum structures
* Implemented analysis to compute minimum structures
* Bridge code that creates the minimum captures (preserves current behavior for `let _ = x` when feature gate is not present)
* How is it being tested? Gone through individual tests by hand and checked that they're fine thus far.

Action items:

* To select new algorithm, should add feature gate `capture_disjoint_fields` and use that to decide instead of environment variable.
* Testing system based on the `rustc_variance`-like attributes, where you would have a `rustc_minimum_captures` attribute that dumps the minimum captures for each closure in the form of special warnings or errors.
